FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
CGO_ENABLED=1 go build -race -o /app/kubeportal

FROM debian:trixie
ENV GODEBUG=http2debug=1
COPY --from=builder /app/kubeportal /app/kubeportal
ENTRYPOINT ["/app/kubeportal"]
