# allow client to use a remote virtual user named testUser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: client
  namespace: default
rules:
  - apiGroups: ["kubeportal.ibm.com"]
    resources: ["remoteUsers"]
    resourceNames: ["testUser"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client
  namespace: default
subjects:
  - kind: ServiceAccount
    name: client
    namespace: default
roleRef:
  kind: Role
  name: client
  apiGroup: rbac.authorization.k8s.io