{{- if .Values.clusterCASync.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fullname" . }}-openid-ca-certs
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.clusterCASync.secretStoreRef.name }}
    kind: {{ .Values.clusterCASync.secretStoreRef.kind }}
  target:
    name: {{ .Values.clusterCACerts.name }}
  {{- with .Values.clusterCASync.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

